### ISSUE TITLE
`autobahntestsuite` triggering error on CI

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaWeb/HTTP.jl#951]
https://github.com/JuliaWeb/HTTP.jl/actions/runs/3363509047/jobs/5576753808

```
  python -m pip install --upgrade pip autobahntestsuite
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/2.7.18/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/2.7.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/2.7.18/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/2.7.18/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/2.7.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/2.7.18/x64/lib
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already up-to-date: pip in /opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages (20.3.4)
Collecting autobahntestsuite
  Downloading autobahntestsuite-0.8.2-py2.py3-none-any.whl (1.4 MB)
Collecting autobahn[accelerate,twisted]==0.10.9
  Downloading autobahn-0.10.9.tar.gz (158 kB)
Collecting klein>=0.2.1
  Downloading klein-20.6.0-py2.py3-none-any.whl (118 kB)
Collecting Werkzeug>=0.9.4
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting service-identity>=14.0.0
  Downloading service_identity-21.1.0-py2.py3-none-any.whl (12 kB)
Collecting markupsafe>=0.19
  Downloading MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl (24 kB)
Collecting pyopenssl>=0.14
  Downloading pyOpenSSL-21.0.0-py2.py3-none-any.whl (55 kB)
Collecting unittest2>=1.1.0
  Downloading unittest2-1.1.0-py2.py3-none-any.whl (96 kB)
Collecting txaio<=2.1.0
  Downloading txaio-2.1.0.tar.gz (32 kB)
Collecting jinja2>=2.6
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Requirement already satisfied, skipping upgrade: setuptools in /opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages (from autobahntestsuite) (41.2.0)
Collecting six>=1.9.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting wsaccel>=0.6.2
  Downloading wsaccel-0.6.4.tar.gz (220 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/2.7.18/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-UEPAx2/wsaccel/setup.py'"'"'; __file__='"'"'/tmp/pip-install-UEPAx2/wsaccel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3mrsZq
         cwd: /tmp/pip-install-UEPAx2/wsaccel/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-UEPAx2/wsaccel/setup.py", line 50, in <module>
        with open('README.rst', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Error: Process completed with exit code 1.```

**Comment by quinnj** [comment]
Ugh, I was worried this was going to happen.

**Comment by quinnj** [comment]
Should be fixed by https://github.com/JuliaWeb/HTTP.jl/pull/953
